import { Header } from '@/components/Header/Header'
import '@/styles/global.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import AuthSession from './api/auth/[...nextauth]/AuthSession'
import Providers from '@/utils/provider'

const mainFont = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet" />
      </head>
      <body className={mainFont.className}>
        <AuthSession>
          <Providers>
            <Header />
            {children}
          </Providers>
        </AuthSession>
      </body>
    </html>
  )
}
