import { Header } from '@/components'
import '@/styles/global.css'

import type { Metadata } from 'next'

import localFont from 'next/font/local'

const mainFont = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
